name: Test Ollama Hub Push

on:
  workflow_dispatch:  # Manual trigger for testing

jobs:
  test-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Ollama
      run: |
        curl -fsSL https://ollama.com/install.sh | sh
        
    - name: Start Ollama server
      run: |
        ollama serve &
        sleep 5  # Wait for server to start

    - name: Debug SSH setup
      run: |
        echo "Public Key:"
        echo "${{ secrets.OLLAMA_SSH_PUBLIC_KEY }}"
        echo "Private Key (first few characters):"
        echo "${{ secrets.OLLAMA_SSH_PRIVATE_KEY }}" | head -c 20
        echo "Username:"
        echo "${{ secrets.OLLAMA_USERNAME }}"

    - name: Set up SSH for Ollama
      run: |
        mkdir -p ~/.ollama
        echo "${{ secrets.OLLAMA_SSH_PRIVATE_KEY }}" > ~/.ollama/id_ed25519
        chmod 600 ~/.ollama/id_ed25519
        # Also save public key for debugging
        echo "${{ secrets.OLLAMA_SSH_PUBLIC_KEY }}" > ~/.ollama/id_ed25519.pub
        chmod 644 ~/.ollama/id_ed25519.pub
        
        echo "SSH directory contents:"
        ls -la ~/.ollama/

    - name: Create and push test model
      env:
        OLLAMA_USERNAME: ${{ secrets.OLLAMA_USERNAME }}
      run: |
        # Create a simple test model
        echo "FROM gemma:2b" > Modelfile
        echo "PARAMETER temperature 0.7" >> Modelfile
        
        # Create local model
        ollama create test-model -f Modelfile
        
        # Tag with username
        FINAL_NAME="${OLLAMA_USERNAME}/test-model:test"
        echo "Tagging model as: $FINAL_NAME"
        ollama cp test-model "$FINAL_NAME"
        
        # Try to push
        echo "Pushing model to Ollama Hub..."
        ollama push "$FINAL_NAME"

    - name: Clean up
      if: always()
      run: |
        pkill ollama || true
        ollama rm test-model || true
