name: Debug Ollama Push

on:
  workflow_dispatch:

jobs:
  debug-push:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/devcontainers/base:ubuntu
      options: --user vscode

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ollama environment
      run: |
        # Create Ollama directories with correct permissions
        sudo mkdir -p /home/vscode/.ollama
        sudo chown -R vscode:vscode /home/vscode/.ollama
        
        # Set up SSH keys
        echo "${{ secrets.OLLAMA_SSH_PRIVATE_KEY }}" > /home/vscode/.ollama/id_ed25519
        echo "${{ secrets.OLLAMA_SSH_PUBLIC_KEY }}" > /home/vscode/.ollama/id_ed25519.pub
        chmod 600 /home/vscode/.ollama/id_ed25519
        chmod 644 /home/vscode/.ollama/id_ed25519.pub
        
        echo "Ollama directory setup:"
        ls -la /home/vscode/.ollama/

    - name: Install Ollama
      run: curl -fsSL https://ollama.com/install.sh | sh

    - name: Start Ollama server
      run: |
        # Kill any existing Ollama processes
        pkill ollama || true
        sleep 2
        
        # Start server with debug
        OLLAMA_DEBUG=1 ollama serve &
        sleep 5
        
        # Verify server
        curl -v http://localhost:11434/api/tags

    - name: Create and push test model
      env:
        OLLAMA_DEBUG: 1
      run: |
        # Create minimal model
        cat > Modelfile << 'EOF'
        FROM gemma:2b
        PARAMETER temperature 0.7
        EOF
        
        # Create local model
        echo "Creating model..."
        ollama create test-debug -f Modelfile
        
        # Copy with namespace
        echo "Copying model with namespace..."
        ollama cp test-debug llm_hub/test-debug
        
        # List models to verify
        echo "Listing models:"
        ollama list
        
        # Push using the namespaced name
        echo "Pushing model..."
        OLLAMA_DEBUG=1 ollama push llm_hub/test-debug
        
        echo "Model should be available at: https://ollama.com/llm_hub/test-debug"
        
    - name: Debug info on failure
      if: failure()
      run: |
        echo "Environment:"
        env | grep -i ollama || true
        whoami
        pwd
        
        echo "\nOllama directory:"
        ls -la /home/vscode/.ollama/
        
        echo "\nOllama logs:"
        cat /home/vscode/.ollama/logs/ollama.log || true
        
        echo "\nProcess status:"
        ps aux | grep ollama
        
        echo "\nModel files:"
        ls -R /home/vscode/.ollama/models/ || true
        
        echo "\nNetwork connections:"
        sudo netstat -tupn | grep ollama || true
        
        echo "\nTesting registry connection:"
        curl -v https://registry.ollama.com/v1/auth || true

    - name: Clean up
      if: always()
      run: |
        pkill ollama || true
        ollama rm test-debug || true
        ollama rm llm_hub/test-debug || true
