name: Debug Ollama Push

on:
  workflow_dispatch:

jobs:
  debug-push:
    runs-on: ubuntu-latest
    steps:
    - name: Install Ollama
      run: |
        curl -fsSL https://ollama.com/install.sh | sh

    - name: Start Ollama server
      run: |
        # Kill any existing Ollama processes
        pkill ollama || true
        sleep 2
        
        # Start server with debug
        OLLAMA_DEBUG=1 ollama serve &
        sleep 5
        
        # Verify server
        curl -v http://localhost:11434/api/tags

    - name: Create and push test model
      env:
        OLLAMA_DEBUG: 1
      run: |
        # Create minimal model
        cat > Modelfile << 'EOF'
        FROM gemma:2b
        PARAMETER temperature 0.7
        EOF
        
        # Create local model
        echo "Creating model..."
        ollama create test-debug -f Modelfile
        
        # Copy with namespace
        echo "Copying model with namespace..."
        ollama cp test-debug llm_hub/test-debug
        
        # List models to verify
        echo "Listing models:"
        ollama list
        
        # Push using the namespaced name
        echo "Pushing model..."
        ollama push llm_hub/test-debug
        
    - name: Debug info on failure
      if: failure()
      run: |
        echo "Ollama logs:"
        cat ~/.ollama/logs/ollama.log || true
        
        echo "\nProcess status:"
        ps aux | grep ollama
        
        echo "\nModel files:"
        ls -R ~/.ollama/models/ || true
        
        echo "\nNetwork connections:"
        netstat -tupn | grep ollama || true

    - name: Clean up
      if: always()
      run: |
        pkill ollama || true
        ollama rm test-debug || true
        ollama rm llm_hub/test-debug || true
